FROM mcr.microsoft.com/devcontainers/base:debian
# Install install packages necessary for ffmpeg crosscompile build
RUN apt-get update && apt-get install -y subversion ragel curl texinfo g++ ed bison flex cvs yasm automake libtool autoconf gcc cmake git make pkg-config zlib1g-dev unzip pax nasm gperf autogen bzip2 autoconf-archive p7zip-full meson clang libtool-bin ed python3-distutils python-is-python3
