name: ShellCheck Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-check
          filter_mode: nofilter
          path: ffmpeg-windows-build-helpers/cross_compile_ffmpeg.sh
